export enum ProjectStatus {
  INITIALIZING = 'INITIALIZING',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  MIGRATING = 'MIGRATING',
  MAINTENANCE = 'MAINTENANCE',
  UPDATING = 'UPDATING',
  DELETING = 'DELETING',
  ERROR = 'ERROR',
  DELETED = 'DELETED',
}
